name: Deploy to Vercel

on:
  push:
    branches:
      - main   # branch mà bạn muốn trigger deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Deploy Hook
        run: |
          curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_nNw7pAvqZWA2rAUWGNZeVV9H5QSG/MIb4jo9LwS
